version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_NAME=voting_saas
      - DB_USER=postgres
      - DB_PASS=admin
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: voting_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: